# @package _global_
defaults:
    - override /datasets: robomimic

tokenizers:
    states:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
    actions:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
    rewards:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
    returns:
      _target_: research.mtm.tokenizers.continuous.ContinuousTokenizer.create
      
# configuration example for robomic 
# args:
#     batch_size: 128
#     eval_every: 500
#     warmup_steps: 100
#     num_train_steps: 1010
#     traj_length: 4
